import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
            //Integrating scanner.
        Scanner scan = new Scanner(System.in);

            //Printing welcome + choice message.
        System.out.println("Choose rock, paper, or scissors. \n \'r\' for rock, \'p\' for paper, or \'s\' for scissors.");

            //Setting a variable to scan and collect the move made by the player.
        String humanMove = (scan.next());

            //Setting a variable to the random move generated by the computer.
        String computerMove = "";

            //Generating a random number from 0 to 3 and round into an integer for the possibilities of 0, 1, and 2.
        int random = (int)(Math.random()*3);

            //Assigning a corresponding letter, either r, p, or s, to the random numbers of 0, 1, and 2.
        if (random == 0) {
            computerMove = "r";
        }
        else if (random == 1) {
            computerMove = "p";
        }
        else {
            computerMove = "s";
        }

            //Checking if the player's move is valid then printing the results based on the choices of the player in correspondence with the computer's move.
        if (!humanMove.equals("r") && !humanMove.equals("p") && !humanMove.equals("s")) {
            System.out.println("Invalid selection. Please play again.");
            }
        else if (humanMove.equals(computerMove)) {
            System.out.println("Draw! \n Computer Choice: " + computerMove + "\t\t" + "Player Choice: " + humanMove);
        }
        else if (humanMove.equals("r") && computerMove.equals("s") || humanMove.equals("s") && computerMove.equals("p") || humanMove.equals("p") && computerMove.equals("r")) {
            System.out.println("You Win! \n Computer Choice: " + computerMove + "\t\t" + "Player Choice: " + humanMove);
        }
        else {
            System.out.println("You Lose! \n Computer Choice: " + computerMove + "\t\t" + "Player Choice: " + humanMove);
        }
    }
}
